Câu 1:

a)

In [45]:
import numpy as np
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([[2, -1, 3], [1, 4, -2], [0, 2, 5]])

print(A + B)
print(2*A + 3*B)

[2 3 1 6]
[ 3 11  2 14]


b)

In [46]:
vohuong = np.dot(A, B)
print(vohuong)
goc = np.arccos(vohuong / (np.linalg.norm(A) * np.linalg.norm(B)))
print(goc)


-5
1.7382444060145859


c)

In [47]:
C_CT = np.dot(C, C.T)
print(C_CT)

[[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


câu 2

a)

In [48]:
M = np.array([[2, -1, 3, 0],
              [1, 4, -2, 5],
              [0, 2, 6, -3],
              [-1, 0, 1, 4]])

N = np.array([[1, 3, -2, 0],
              [4, -1, 5, 2],
              [0, 2, 3, -1],
              [-3, 1, 0, 4]])
print(M.dot(N))

[[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]


b)

In [49]:
det_M = round(np.linalg.det(M), 3)
print(det_M)

409.0


c)

In [50]:
hang_N = np.linalg.matrix_rank(N)
print(hang_N)

4


câu 3:

a)

In [51]:
P = np.array([[3, -1, 0, 2],
              [1, 4, -2, 0],
              [0, 1, 5, -1],
              [2, 0, 1, 3]])

b = np.array([6, 8, 3, 7])
if round(np.linalg.det(P), 6) != 0:
    P_inv = np.linalg.inv(P)
    print(P_inv)
else:
    print("Ma trận P không khả nghịch.")

[[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]


b)

In [52]:
b = np.array([6, 8, 3, 7])
x = np.linalg.solve(P, b)
print(x)

[2.         1.71428571 0.42857143 0.85714286]


c)

In [53]:
kiemtra = np.dot(P, x)
print(kiemtra)
print(np.allclose(kiemtra, b))

[6. 8. 3. 7.]
True


câu 4
a)

In [54]:
Q = np.array([[5, -2, 1],
              [0, 3, -1],
              [2, 0, 4]])
GiaTriRieng = np.linalg.eig(Q)
print(GiaTriRieng)

EigResult(eigenvalues=array([6.3553014+0.j        , 2.8223493+1.07730381j,
       2.8223493-1.07730381j]), eigenvectors=array([[ 0.74846013+0.j        , -0.37423006+0.34234215j,
        -0.37423006-0.34234215j],
       [-0.18941773+0.j        ,  0.09470887+0.57433055j,
         0.09470887-0.57433055j],
       [ 0.63555359+0.j        ,  0.63555359+0.j        ,
         0.63555359-0.j        ]]))


b)

In [55]:
vecRieng = np.linalg.eig(Q)
print(vecRieng)

EigResult(eigenvalues=array([6.3553014+0.j        , 2.8223493+1.07730381j,
       2.8223493-1.07730381j]), eigenvectors=array([[ 0.74846013+0.j        , -0.37423006+0.34234215j,
        -0.37423006-0.34234215j],
       [-0.18941773+0.j        ,  0.09470887+0.57433055j,
         0.09470887-0.57433055j],
       [ 0.63555359+0.j        ,  0.63555359+0.j        ,
         0.63555359-0.j        ]]))


c)


In [56]:
vecChuanhoa = vecRieng[1] / np.linalg.norm(vecRieng[1], axis=0)
print(vecChuanhoa)

[[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]


câu 5

a)

In [57]:
R = np.array([[4, -1, 2],
              [1, 3, -2],
              [0, 2, 5]])
b = np.array([12, 5, 9])
x1 = np.linalg.solve(R, b)
print(x1)

[2.78823529 1.52941176 1.18823529]


b)

In [58]:
if round(np.linalg.det(R), 6) != 0:
    R_inv = np.linalg.inv(R)
    x2 = np.dot(R_inv, b)
    print(R_inv)
    print(x2)
    print(np.allclose(x1, x2))
else:
    print("R không khả nghịch.")

[[ 0.22352941  0.10588235 -0.04705882]
 [-0.05882353  0.23529412  0.11764706]
 [ 0.02352941 -0.09411765  0.15294118]]
[2.78823529 1.52941176 1.18823529]
True


c)

In [59]:
Chuan_R = np.linalg.norm(R)
print(round(Chuan_R, 3))

8.0
