In [22]:
import numpy as np
u = np.array([2,-1,5,0])
v = np.array([4,3,1,-1])
w = np.array([-6,2,0,3])
x = 2*u-(v+3*w)
print (x)

[ 18 -11   9  -8]


In [23]:
x = 0.5*(2*u-v-3*w)
print(x)

[ 9.  -5.5  4.5 -4. ]


In [24]:
from numpy import linalg
A = np.matrix([[0, -1, 3],[1, 1, 1],[4, 2, 2]])
B = np.array([-1, -2, -2])
X = np.linalg.solve(A, B)
print (X)

[ 1. -2. -1.]


In [25]:
A = np.matrix([[1,0],[0,0]])
B = np.matrix([[0,0],[0,1]])
from numpy import linalg as LA
print(LA.inv(A))

LinAlgError: Singular matrix

In [ ]:
print(LA.inv(B))


LinAlgError: Singular matrix

In [26]:

print(LA.inv(A+B))

[[1. 0.]
 [0. 1.]]


In [27]:
print(LA.det(A))

0.0


In [28]:
print(LA.det(B))

0.0


In [29]:
print(LA.det(A+B))

1.0


In [30]:
import sympy as sp
x, y = sp.symbols('x y')
A = sp.Matrix([[x, y],[y, x]])
x1, y1 = sp.symbols('x1 y1')
A1 = sp.Matrix([[x1, y1],[y1, x1]])
x2, y2 = sp.symbols('x2 y2')
A2 = sp.Matrix([[x2, y2],[y2, x2]])
A1.T

Matrix([
[x1, y1],
[y1, x1]])

In [31]:
print((A1+A2).T)

Matrix([[x1 + x2, y1 + y2], [y1 + y2, x1 + x2]])


In [32]:
((A1+A2).T).equals(A1+A2)

True

In [33]:
c = sp.symbols('c')
print (c*A)

Matrix([[c*x, c*y], [c*y, c*x]])


In [34]:
print(((c*A).T).equals(c*A))

True


In [35]:
import numpy as np

v1 = [1, 2, 3]
v2 = [0, 1, 2]
v3 = [-1, 0, 1]
A = np.column_stack((v1, v2, v3))
w1 = np.array([1, 1, 1])
sol1 = np.linalg.lstsq(A, w1, rcond=None)
print("Nghiệm cho câu a:", sol1[0]) 
w2 = np.array([1, -2, 2])
sol2 = np.linalg.lstsq(A, w2, rcond=None)
print("Nghiệm cho câu b:", sol2[0])
print("Sai số bình phương:", sol2[1])


Nghiệm cho câu a: [ 5.00000000e-01  3.55887906e-16 -5.00000000e-01]
Nghiệm cho câu b: [0.08333333 0.16666667 0.25      ]
Sai số bình phương: []


In [36]:
import sympy as sp
c1, c2, c3 = sp.symbols('c1 c2 c3')
sp.solve([c1-2*c3, 2*c1+c2, 3*c1+2*c2+c3], [c1, c2, c3])

{c1: 0, c2: 0, c3: 0}

In [37]:
import sympy as sp
c1, c2 = sp.symbols('c1 c2')
u1, u2 = sp.symbols('u1 u2')
sp.solve([c1+c2-u1,c1-c2-u2])

{c1: u1/2 + u2/2, c2: u1/2 - u2/2}

In [38]:
u1 = 0
u2 = 0
sp.solve([c1+c2-u1,c1-c2-u2])

{c1: 0, c2: 0}

In [39]:
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,2])
P_caua = (P.T + vecdelta).T # lệnh này sinh viên nên tách làm từng lệnh để hiểu
print (P_caua)

[[4 4 7 7 5 5 6 6 5 5]
 [2 7 7 6 6 5 5 4 4 2]]


In [40]:
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,-2])
matran_biendoi = np.array([[1.0, 0.0],[0.0, 2.0]])
P_caub = (P.T @ matran_biendoi + vecdelta).T
print (P_caub)

[[ 4.  4.  7.  7.  5.  5.  6.  6.  5.  5.]
 [-2.  8.  8.  6.  6.  4.  4.  2.  2. -2.]]


In [41]:
import sympy as sp
from sympy import lambdify
x1, x2, x3 = sp.symbols('x1 x2 x3')
bieuthuc1 = x1 - x2 + x3
f1 = lambdify([x1, x2, x3], bieuthuc1, 'numpy')
a, b, c = sp.symbols('a b c') # khai báo thêm 3 biến a, b, c giả định X = (a, b, c)
d, e, f = sp.symbols('d e f') # khai báo thêm 3 biến d, e, f giả định Y = (e, d, f)
f1(a, b, c)

a - b + c

In [42]:
f1(d, e, f)

d - e + f

In [43]:
f1(a+d, b+e, c+f)

a - b + c + d - e + f

In [44]:
f1(a,b,c) + f1(d,e,f) == f1(a+d, b+e, c+f)

True

In [45]:
(f1(a,b,c) + f1(d,e,f)).equals( f1(a+d, b+e, c+f))

True

In [46]:
q = sp.symbols('q')
(q*f1(a,b,c) + f1(d,e,f)).equals(f1(q*a+d, q*b+e, q*c+f).expand())

True

In [48]:
bieuthuc2 = 2*x2 + 3* x3
f2 = lambdify([x1, x2, x3], bieuthuc2, 'numpy')
(q*f2(a,b,c) + f2(d,e,f)).equals(f2(q*a+d, q*b+e, q*c+f).expand())


True

In [49]:
import sympy as sp
a, b = sp.symbols('a b')
x, y = sp.symbols('x y')
sp.solve([a+3*b-x, 2*a+5*b-y],[a,b])

{a: -5*x + 3*y, b: 2*x - y}

In [50]:
fu1 = np.array([1,1,2])
fu2 = np.array([4,2,1])
fu = a*fu1 + b*fu2
print (fu)

[a + 4*b a + 2*b 2*a + b]


In [51]:
fu = a.subs(a, -5*x + 3*y)*fu1 + b.subs(b, 2*x - y)*fu2 # thay giá trị tìm được ở trên vào
print (fu)

[3*x - y -x + y -8*x + 5*y]


In [ ]:
# sinh viên ghi kết quả (đúng hoặc sai)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         R                                                                                                                                                                                        b 