In [33]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b) # tích vô hướng
print (tich)

32


In [34]:
tich1 = np.dot(a,b) 
print(tich1)

32


In [35]:
import numpy as np
a = np.array([1,2,-3])
print(np.linalg.norm(a))

3.7416573867739413


In [36]:
a = np.array([1,2,-3])
print(np.linalg.norm(a,1))

6.0


In [37]:
def chuan(v,k):
    tong = 0 
    for i in range(len(v)):
        tong = tong + abs(v[i]**k)
    ketqua = math.pow(tong, 1.0/k)
    return ketqua
import math
import numpy as np
a = np.array([1,2,-3])
chuan(a, 1)

6.0

In [38]:
print(np.linalg.norm(a,1))

6.0


In [39]:
print(chuan(a, 2))

3.7416573867739413


In [40]:
print(np.linalg.norm(a,2))

3.7416573867739413


In [41]:
print(chuan(a, 3))

3.3019272488946263


In [42]:
print(np.linalg.norm(a,3))

3.3019272488946263


In [43]:
print(chuan(a, 1000))

1.0442214818467515


In [44]:
print(np.linalg.norm(a,1000))

inf


In [45]:
from scipy import linalg
print(linalg.norm(a))

3.7416573867739413


In [46]:
print(linalg.norm(a, 100))

3.0


In [47]:
print(linalg.norm(a, 1000))

inf


In [48]:
import numpy as np
m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([2,5,2,1])
M = np.array([v1,v2,v3,v4])
MT = M.transpose()
print(MT)

[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]


In [49]:
v = (1.0/m)*MT.dot(mi)
print(v)

[1.3 0.9 0. ]


In [50]:
import numpy as np
F = 0.136
J = 0.998
A = np.array([[J, F], [1 - J, 1 - F]])
v0 = np.array([0.95, 0.05])
A_power_100 = np.linalg.matrix_power(A, 100)
v_100 = A_power_100 @ v0
print(round(v_100[0], 4))
print(round(v_100[1], 4))


0.9855
0.0145


In [51]:
import sympy as sym
x, y = sym.symbols('x y')
xy = sym.Matrix([x,y])
A = sym.Matrix([[1, -68],[1,1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A*xy-v])
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [53]:
import numpy as np

A = np.array([[1, 6],
              [5, 2]])
u = np.array([6, -5])
Au = A @ u
minus4u = -4 * u
print("A @ u      =", Au)
print("-4 * u     =", minus4u)

A @ u      = [-24  20]
-4 * u     = [-24  20]


In [54]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])

[-7.000, 3.000]


In [55]:
print (sympy.pretty(nghiem))

[-7, 3]


In [56]:
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg as LA
P1 = LA.inv(P) # tính giá trị nghịch đảo của P
print (P1)

[[-0.3  0.9]
 [ 0.3  0.1]]


In [57]:
print(A.dot(P))

[[ 2.33333333  9.        ]
 [-7.          3.        ]]


In [58]:
print(P.dot(D))

[[ 2.33333333  9.        ]
 [-7.          3.        ]]


In [59]:
kq =P @ (D ** 1000) @ P1
print(kq)

[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]


In [61]:
print(print (D **2))

[[49  0]
 [ 0  9]]
None


In [69]:
#cau1
import numpy as np
a = np.array([1,2,3])
mag = np.sqrt(a @ a )
print(mag)

3.7416573867739413
