In [1]:
import numpy as np
D = np.array([[1,2],[3,4]])
print(np.copyto(E, D))

NameError: name 'E' is not defined

In [2]:
E = np.array([[1,2],[3,5]])
print(np.copyto(E, D))

None


In [3]:
print(E)

[[1 2]
 [3 4]]


In [45]:
x = np.array([['a','b'],['c','d']])
y = 'x'
C = np.array([[x, y], [1, 2]], dtype=object)
print(C)

[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]


In [15]:
A = np.matrix([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A)

ValueError: matrix must be 2-dimensional

In [20]:
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
from numpy import matlib
G = matlib.identity(5)
print(G)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
H = matlib.randn(3,2)
print(H)

[[ 0.45635147  0.51950855]
 [ 0.23055703  1.02501189]
 [ 0.27550144 -0.8053953 ]]


In [23]:
K = matlib.zeros([4,4])
print(K)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2] 
M = np.matrix([[1,2],[3,4]])
for i in range(len(c)):
    ci = np.matrix([[1,1],[1,0]])
    ci[0, 0] = c[i]
    if (i==0):
        M = ci
    else:
        M = M.dot(ci)
print(M)
print (M[0,0]/M[1,0])

[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


In [43]:
X = np.array([[1,1],[1,2],[1,3],[1,4],[1,5]])
Y= np.array([[1],[2],[4],[4],[6]])
XT = X.T
A1 = np.linalg.inv(XT.dot(X))
A2 = XT.dot(Y)
A = A1.dot(A2)
print(A)

[[-0.2]
 [ 1.2]]
