In [ ]:
import scipy.linalg
import numpy as np 
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)]) # số phức
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]]) # ma trận số thực
A = np.matrix(np.random.random( (2,2) ) )
B = np.asmatrix(b) 
C = np.matrix(np.random.random( (10,5) ) )


F = np.eye(3, k=1)
print(a)
print(b)
print(c)
print(A)
print(B)
print(C)
print(D)
print(F)

[1 2 3]
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
[[[ 0.5  1.5 10. ]
  [ 3.   2.   1. ]]

 [[ 6.   5.   4. ]
  [ 7.   8.   9. ]]]
[[0.89877996 0.22183008]
 [0.32802478 0.7365253 ]]
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
[[0.2992535  0.1684886  0.26950333 0.62649868 0.24077177]
 [0.29282703 0.78606718 0.29338624 0.83148197 0.6222813 ]
 [0.49297461 0.21783999 0.42401247 0.33248451 0.78425363]
 [0.71509242 0.87856724 0.49574605 0.93560315 0.94112935]
 [0.44274598 0.07340746 0.3726848  0.36132622 0.91346243]
 [0.19166543 0.45783118 0.13355035 0.06622652 0.55848346]
 [0.36638372 0.8867761  0.57551437 0.51848728 0.55107612]
 [0.43529495 0.26395214 0.70924759 0.63315103 0.32665111]
 [0.91306201 0.39337041 0.63161909 0.6240239  0.55894542]
 [0.18499633 0.92191168 0.25999032 0.22200526 0.71851299]]
[[4 3]
 [2 6]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [8]:
F = np.eye(3, k=0)
print(F)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
F = np.eye(3, k=-1)
print(F)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [10]:
print(np.linalg.matrix_rank(C))

5


In [11]:
print(A.I)

[[ 1.25002508 -0.37648831]
 [-0.55672115  1.52540246]]


In [33]:
import scipy.linalg
a = scipy.linalg.inv(A)
print(a)

[[ 1.25002508 -0.37648831]
 [-0.55672115  1.52540246]]


In [37]:
import scipy.linalg
a = scipy.linalg.det(A)
print(a)

0.5892084133675086


In [38]:
print(A.T)

[[0.89877996 0.32802478]
 [0.22183008 0.7365253 ]]


In [39]:
print(A.H)

[[0.89877996 0.32802478]
 [0.22183008 0.7365253 ]]


In [10]:
import scipy.linalg
import numpy as np 
A = np.matrix(np.random.random( (2,2) ) )
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
a = scipy.linalg.solve(A, b)
print(a)

[[ 2.44942986+10.85409592j  0.         -9.08960632j
   0.         -9.43786967j]
 [-1.47337201 +4.82367955j  0.        +19.65829048j
   0.        +22.70592538j]]


In [12]:
E = np.matrix(a).T
print(E)

[[ 2.44942986+10.85409592j -1.47337201 +4.82367955j]
 [ 0.         -9.08960632j  0.        +19.65829048j]
 [ 0.         -9.43786967j  0.        +22.70592538j]]


In [14]:
F = np.eye(3, k=1)
print( scipy.linalg.lstsq(F, E))

(array([[ 0.         +0.j        ,  0.         +0.j        ],
       [ 2.44942986+10.85409592j, -1.47337201 +4.82367955j],
       [ 0.         -9.08960632j,  0.        +19.65829048j]]), array([], dtype=complex128), 2, array([1., 1., 0.]))


In [16]:
D = np.matrix([ [4, 3], [2, 6] ])
print(np.add(A, D))

[[4.65033181 3.40243887]
 [2.21193966 6.35234234]]


In [17]:
print(np.subtract(A, D))

[[-3.34966819 -2.59756113]
 [-1.78806034 -5.64765766]]


In [18]:
print(np.divide(A, D))

[[0.16258295 0.13414629]
 [0.10596983 0.05872372]]


In [19]:
print(A @ D )

[[3.40620498 4.36562864]
 [1.55244334 2.74987305]]


In [20]:
print(np.multiply(D, A))

[[2.60132725 1.2073166 ]
 [0.42387933 2.11405405]]


In [21]:
print(np.dot(A, D))

[[3.40620498 4.36562864]
 [1.55244334 2.74987305]]


In [22]:
print(np.vdot(A, D))

[[2.60132725]]


In [23]:
print(scipy.linalg.expm(A))

[[1.9908658  0.67636433]
 [0.35619927 1.49004576]]


In [24]:
print(scipy.linalg.logm(A))

[[-0.614033    0.96013597]
 [ 0.50564424 -1.3249743 ]]


In [26]:
import numpy as np
A = np.array([ [0,1], [1,0]])
print(A)

[[0 1]
 [1 0]]


In [27]:
temp = A.dot(A)
print(temp)

[[1 0]
 [0 1]]


In [28]:
k= 6
for i in range(k-1):
    temp = temp.dot(A)
    print (temp)
    print('---')

[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---


In [29]:
B = np.array([ [0,-1], [-1,0]])
print(B)

[[ 0 -1]
 [-1  0]]


In [30]:
temp = B.dot(B)
print(temp)

[[1 0]
 [0 1]]


In [31]:
k= 5
for i in range(k-1):
    temp = temp.dot(B)
    print (temp)
    print('---')

[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---


In [32]:
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C)

[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]


In [33]:
temp = C.dot(C) 
print(temp)

[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]


In [34]:
k= 1000
for i in range(k-1):
    temp = temp.dot(C)
print(temp)

[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]


In [35]:
k= 1000
for i in range(k-1):
    temp = temp.dot(C)
print(temp)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [36]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M) # tính M2, nghĩa là M2
print (MM)

[[0.7  0.45]
 [0.3  0.55]]


In [37]:
MM = M.dot(M) # tính M3
print (MM)

[[0.7  0.45]
 [0.3  0.55]]


In [54]:
for i in range(100): # tính các M^ khác.
    MM = MM.dot(M) # tính M^n
print (MM) # kết luận xu hướng của M

[[0.6 0.6]
 [0.4 0.4]]


In [39]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = scipy.linalg.lu(M) # lệnh lina.lu sẽ tách ma trận M thành 3 ma trận P, L và U
print(P)

[[1. 0.]
 [0. 1.]]


In [40]:
print(L)

[[1.   0.  ]
 [0.25 1.  ]]


In [41]:
print(U)

[[0.8   0.3  ]
 [0.    0.625]]


In [42]:
print(L.dot(U))

[[0.8 0.3]
 [0.2 0.7]]


In [43]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])

In [44]:
temp = A.dot(A) # lúc này temp = õÜ
print(temp)


[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]


In [45]:
temp = temp.dot(A)
print(temp) # lúc này temp = õÜ^2

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [48]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
print(temp) 


[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]


In [49]:
k = 3
sumA = sumA + temp
for i in range(1, k-1):
    temp = temp.dot(A)
    sumA = sumA + temp
print (temp)


[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [50]:
print(sumA)

[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]
