BÀI TẬP CHƯƠNG 2

In [ ]:
#bài 1.
def scale(a, v):
    return [a*vi for vi in v]
v = [3,5,7]
st1 = scale(10, v)
print(st1)

[30, 50, 70]


In [ ]:
#bài 2
def sumvector(v, w):
    return [vi+wi for (vi, wi) in zip(v,w)]
v=[3,5,7]
w=[2,4,6]
sumvector(v, w)

[5, 9, 13]


In [ ]:
#bài 3
def dotvector(v, w):
    return sum([vi*wi for (vi, wi) in zip(v, w)])
print(dotvector(v, w))

68


In [ ]:
#bài 4
def lenvector(v):
    return dotvector(v,v)
print(lenvector(w))

56


In [ ]:
#bài 5
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
print(scores >=0)
print(scores < 0)
print(np.select([scores >=0, scores < 0],['so duong','so am'], default='khong phai so duong hoac so am')) # phải thêm default nếu không sẽ báo lỗi khi không có điều kiện nào đúng


[False  True  True False  True False]
[ True False False  True False  True]
['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']


In [59]:
#bài 6
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
np.select([scores >0, scores ==0, scores < 0],['so duong', 'so 0', 'so am'], default='khong phai so duong, so 0 hoac so am')

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U36')

In [60]:
#bài 7
import numpy as np
from scipy import linalg, sparse
D = np.matrix([[3,4], [5,6]]) #np.mat ko nên dùng nữa, thay bằng np.matrix
print(D)

[[3 4]
 [5 6]]


In [ ]:
C =np.matrix(np.random.random((5,7)))
print(C)

[[0.36245183 0.32437046 0.28331451 0.10456218 0.30867463 0.30458656
  0.39950296]
 [0.86944465 0.7639654  0.32063148 0.24623639 0.7029384  0.32585056
  0.49791472]
 [0.47698747 0.90950912 0.16459021 0.48921333 0.62162914 0.09269485
  0.94316986]
 [0.64426899 0.70174927 0.85896061 0.08953584 0.46915141 0.32672843
  0.02085114]
 [0.57232567 0.54794725 0.40088019 0.71084568 0.73037337 0.09038715
  0.92649549]]


In [63]:
A = np.matrix(np.random.random((2,2)))
print(A)

[[0.95335382 0.75702315]
 [0.03857916 0.10369447]]


In [76]:
b = np.array([(1+5j, 2j, 3j),(4, 5, 6)])
B = np.asmatrix(b)
print(b)


[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [77]:
print(B)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [78]:
print(A.T)

[[0.95335382 0.03857916]
 [0.75702315 0.10369447]]


In [79]:
print(A.I)

[[  1.48874644 -10.86861787]
 [ -0.5538828   13.68734663]]


In [80]:
#Hoặc sử dụng lệnh của thư viện scipy
print(linalg.inv(A))  # Tính ma trận nghịch đảo của A

[[  1.48874644 -10.86861787]
 [ -0.5538828   13.68734663]]


In [81]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_lower = np.tril(M)
print(M_lower)

[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [82]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_upper = np.triu(M)
print(M_upper)

[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [83]:
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
v_diag = np.diag(M) #vector đường chéo
print (v_diag)

[-1 -2 -2]


In [84]:
M_diag = np.diag(v_diag)
print (M_diag)

[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [85]:
I2 = np.identity(2)
print(I2)

[[1. 0.]
 [0. 1.]]


In [87]:
import sympy as sp
x = sp.symbols('x')
y = sp.symbols('y')
z = sp.symbols('z')
print(sp.solve([x*x+2-6, y - 1 -6 , x+z-1 , 2*x*x-8, z*z+4-5, y-z-8],  [x, y, z])) 

[(2, 7, -1)]


In [88]:
x =[1, 2, 3]
y = [1, 2, 3]
print (all([x[i]==y[i] for i in range(len(x))]))

True


In [89]:
x =[1, 2, 3]
y = [1, 2, 4]
print (all([x[i]==y[i] for i in range(len(x))]))

False


In [90]:
import numpy as np
at = np.array_equal([1,2], [1,2])
print(at)

True


In [116]:
aw = np.array_equal(np.array([1,2]), np.array([1,2]))
print(aw)

True


In [117]:
import numpy as np
A = np.reshape(np.arange(36.0), (6,6))
print(A)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [118]:
I6 = np.identity(6)
print(I6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [120]:
print(A.size)

36


In [121]:
print(np.matrix.diagonal(A))

[ 0.  7. 14. 21. 28. 35.]


In [122]:
A = A + I6
print(A)

[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]
