Câu 1:

In [1]:
import numpy as np
A = np.array([2,-1,3,0])
B = np.array([1,4,-2,5])
C = np.array([[1,2,-1],[0,3,4],[2,-1,0]])

# a) A+B and 3A-2B
sum_AB = A + B
diff_combo = 3*A - 2*B

# b) dot product and angle
dot_AB = np.dot(A,B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_AB / (norm_A * norm_B)
angle_deg = np.degrees(np.arccos(cos_theta))

# c) C^T C
CtC = C.T @ C

(sum_AB, diff_combo, dot_AB, angle_deg, CtC)

(array([3, 3, 1, 5]),
 array([  4, -11,  13, -10]),
 np.int64(-8),
 np.float64(108.3755542856849),
 array([[ 5,  0, -1],
        [ 0, 14, 10],
        [-1, 10, 17]]))

câu 2

In [2]:
M = np.array([[1,2,3,0],
              [4,5,6,1],
              [7,8,9,2],
              [0,1,1,0]])

N = np.array([[0,1,2,3],
              [4,5,6,7],
              [8,9,10,11],
              [12,13,14,15]])

# a) MxN
product = M @ N

# b) det(M)
det_M = np.linalg.det(M)

# c) rank(N)
rank_N = np.linalg.matrix_rank(N)

(product, det_M, rank_N)

(array([[ 32,  38,  44,  50],
        [ 80,  96, 112, 128],
        [128, 154, 180, 206],
        [ 12,  14,  16,  18]]),
 np.float64(3.330669073875464e-16),
 np.int64(2))

In [3]:
P = np.array([[2,1,0,1],
              [0,3,1,-1],
              [1,0,4,2],
              [0,1,0,3]])

b = np.array([4,7,9,5])

# a) Check inverse
det_P = np.linalg.det(P)
is_invertible = det_P != 0

if is_invertible:
    P_inv = np.linalg.inv(P)
else:
    P_inv = None

# b) Solve system using inverse
solution = None
if P_inv is not None:
    solution = P_inv @ b

# c) Check
check = None
if solution is not None:
    check = P @ solution

(det_P, is_invertible, P_inv, solution, check)

(np.float64(86.00000000000004),
 np.True_,
 array([[ 0.48837209, -0.09302326,  0.02325581, -0.20930233],
        [ 0.03488372,  0.27906977, -0.06976744,  0.12790698],
        [-0.11627907,  0.06976744,  0.23255814, -0.09302326],
        [-0.01162791, -0.09302326,  0.02325581,  0.29069767]]),
 array([0.46511628, 2.10465116, 1.65116279, 0.96511628]),
 array([4., 7., 9., 5.]))

câu 3:

In [4]:
Q = np.array([[4,-1,0],
              [1,3,-2],
              [0,1,2]])

# a) eigenvalues, eigenvectors
eigvals, eigvecs = np.linalg.eig(Q)

# normalize eigenvectors
normed_vecs = eigvecs / np.linalg.norm(eigvecs, axis=0)

(eigvals, eigvecs, normed_vecs)

(array([3.45339765+0.j        , 2.77330117+1.46771151j,
        2.77330117-1.46771151j]),
 array([[0.83327121+0.j        , 0.26206044+0.31354813j,
         0.26206044-0.31354813j],
        [0.455468  +0.j        , 0.78166743+0.j        ,
         0.78166743-0.j        ],
        [0.31338154+0.j        , 0.21963176-0.41685708j,
         0.21963176+0.41685708j]]),
 array([[0.83327121+0.j        , 0.26206044+0.31354813j,
         0.26206044-0.31354813j],
        [0.455468  +0.j        , 0.78166743+0.j        ,
         0.78166743-0.j        ],
        [0.31338154+0.j        , 0.21963176-0.41685708j,
         0.21963176+0.41685708j]]))

câu 4:

In [5]:
R = np.array([[1,-2,3],
              [2,0,1],
              [-1,1,4]])
b = np.array([10,8,7])

# a) solve
solution1 = np.linalg.solve(R,b)

# b) invertibility
det_R = np.linalg.det(R)
is_invertible = det_R != 0
if is_invertible:
    R_inv = np.linalg.inv(R)
    solution2 = R_inv @ b
else:
    R_inv = None
    solution2 = None

# c) Frobenius norm
fro_norm = np.linalg.norm(R,'fro')

(solution1, solution2, det_R, fro_norm)

(array([2.7826087 , 0.04347826, 2.43478261]),
 array([2.7826087 , 0.04347826, 2.43478261]),
 np.float64(23.0),
 np.float64(6.082762530298219))